apiVersion: v1
kind: Service
metadata:
  name: josso-server-svc
  labels:
    app: josso-server
spec:
  type: ClusterIP
  selector:
    app: josso-server
  ports:
    - name: http-josso-ports
      port: 8081
      targetPort: 8081
      protocol: TCP

